# .github/workflows/maven-build-and-snyk-scan.yml
name: Build Java Application and Run Snyk Scan

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project
      - name: Build with Maven
        run: mvn package

      # Step 5: Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Step 6: Authenticate Snyk CLI
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_API_TOKEN }}

      # Step 7: Run Snyk scan
      - name: Run Snyk Scan
        run: snyk test
